
public class Encryption {

	public static String encrypt(String i)
	{
		String ii = "owen";
		switch(i)
		{
		case "a": ii = "%";
		break;
		case "b": ii = "b";
		break;
		case "c": ii = "f";
		break;
		case "d": ii = "$";
		break;
		case "e": ii = ">";
		break;
		case "f": ii = "5";
		break;
		case "g": ii = ")";
		break;
		case "h": ii = "K";
		break;
		case "i": ii = ",";
		break;
		case "j": ii = "Q";
		break;
		case "k": ii = "z";
		break;
		case "l": ii = "T";
		break;
		case "m": ii = "/";
		break;
		case "n": ii = "F";
		break;
		case "o": ii = "!";
		break;
		case "p": ii = "6";
		break;
		case "q": ii = "(";
		break;
		case "r": ii = "]";
		break;
		case "s": ii = "P";
		break;
		case "t": ii = "j";
		break;
		case "u": ii = "S";
		break;
		case "v": ii = "N";
		break;
		case "w": ii = "&";
		break;
		case "x": ii = "I";
		break;
		case "y": ii = "2";
		break;
		case "z": ii = "=";
		break;
		

		case "A": ii = "O";
		break;
		case "B": ii = ";";
		break;
		case "C": ii = "[";
		break;
		case "D": ii = "1";
		break;
		case "E": ii = "h";
		break;
		case "F": ii = "A";
		break;
		case "G": ii = "l";
		break;
		case "H": ii = "{";
		break;
		case "I": ii = "'";
		break;
		case "J": ii = "c";
		break;
		case "K": ii = "w";
		break;
		case "L": ii = "D";
		break;
		case "M": ii = "@";
		break;
		case "N": ii = "R";
		break;
		case "O": ii = "v";
		break;
		case "P": ii = "-";
		break;
		case "Q": ii = "e";
		break;
		case "R": ii = "<";
		break;
		case "S": ii = "U";
		break;
		case "T": ii = "*";
		break;
		case "U": ii = "a";
		break;
		case "V": ii = "8";
		break;
		case "W": ii = "k";
		break;
		case "X": ii = "C";
		break;
		case "Y": ii = "^";
		break;
		case "Z": ii = "d";
		break;
		
		case "0": ii = "_";
		break;
		case "1": ii = "L";
		break;
		case "2": ii = "r";
		break;
		case "3": ii = "?";
		break;
		case "4": ii = "Z";
		break;
		case "5": ii = "4";
		break;
		case "6": ii = "|";
		break;
		case "7": ii = "m";
		break;
		case "8": ii = "+";
		break;
		case "9": ii = "i";
		break;
		
		case " ": ii = "#";
		break;
		case "": ii = "`";
		break;
		case "/" : ii = "9";
		break;
		default: ii = "blu";
		break;
		
		}
		return ii;
	}
	
	public static String decrypt(String o)
	{
		String oo = "owen";
		
		switch(o)
		{
		case "%": oo = "a";
		break;
		case "b": oo = "b";
		break;
		case "f": oo = "c";
		break;
		case "$": oo = "d";
		break;
		case ">": oo = "e";
		break;
		case "5": oo = "f";
		break;
		case ")": oo = "g";
		break;
		case "K": oo = "h";
		break;
		case ",": oo = "i";
		break;
		case "Q": oo = "j";
		break;
		case "z": oo = "k";
		break;
		case "T": oo = "l";
		break;
		case "/": oo = "m";
		break;
		case "F": oo = "n";
		break;
		case "!": oo = "o";
		break;
		case "6": oo = "p";
		break;
		case "(": oo = "q";
		break;
		case "]": oo = "r";
		break;
		case "P": oo = "s";
		break;
		case "j": oo = "t";
		break;
		case "S": oo = "u";
		break;
		case "N": oo = "v";
		break;
		case "&": oo = "w";
		break;
		case "I": oo = "x";
		break;
		case "2": oo = "y";
		break;
		case "=": oo = "z";
		break;
		case "O": oo = "A";
		break;
		case ";": oo = "B";
		break;
		case "[": oo = "C";
		break;
		case "1": oo = "D";
		break;
		case "h": oo = "E";
		break;
		case "A": oo = "F";
		break;
		case "l": oo = "G";
		break;
		case "{": oo = "H";
		break;
		case "'": oo = "I";
		break;
		case "c": oo = "J";
		break;
		case "w": oo = "K";
		break;
		case "D": oo = "L";
		break;
		case "@": oo = "M";
		break;
		case "R": oo = "N";
		break;
		case "v": oo = "O";
		break;
		case "-": oo = "P";
		break;
		case "e": oo = "Q";
		break;
		case "<": oo = "R";
		break;
		case "U": oo = "S";
		break;
		case "*": oo = "T";
		break;
		case "a": oo = "U";
		break;
		case "8": oo = "V";
		break;
		case "k": oo = "W";
		break;
		case "C": oo = "X";
		break;
		case "^": oo = "Y";
		break;
		case "d": oo = "Z";
		break;
		case "_": oo = "0";
		break;
		case "L": oo = "1";
		break;
		case "r": oo = "2";
		break;
		case "?": oo = "3";
		break;
		case "Z": oo = "4";
		break;
		case "4": oo = "5";
		break;
		case "|": oo = "6";
		break;
		case "m": oo = "7";
		break;
		case "+": oo = "8";
		break;
		case "i": oo = "9";
		break;
		case "#": oo = " ";
		break;
		case "`": oo = "";
		break;
		case "9" : oo = "/";
		break;
		default: oo = "bluu";
		}
		return oo;
	}
}
